In [ ]:
from sys import exit, stderr
from inspect import currentframe

def debug(*args):
    names = {id(v):k for k,v in currentframe().f_back.f_locals.items()}
    print(', '.join(names.get(id(arg),'???')+' = '+repr(arg) for arg in args), file=stderr)
    return

%timeit [0 for _ in range(10)]
%timeit a.copy()
%env

In [32]:
import numpy as np
H = np.array([[2, 4+1j],[4-1j, 1]])

In [33]:
H

array([[2.+0.j, 4.+1.j],
       [4.-1.j, 1.+0.j]])

In [34]:
H == H.conjugate().T

array([[ True,  True],
       [ True,  True]])

In [35]:
# Hermite matrix has real eigen value
L, P = np.linalg.eig(H)
P

array([[ 0.74846037+0.j        , -0.64337864-0.16084466j],
       [ 0.64337864-0.16084466j,  0.74846037+0.j        ]])

In [36]:
# Hermite matrix's eigen vectors orthogonal
P[:,1].conjugate().T@P[:,0]

(2.220446049250313e-16-8.326672684688674e-17j)