In [22]:
import numpy as np
A = np.array([[1, 2, 3], [2, 3, 1], [3, 1, 2]])
print(A)
print(A.transpose())

[[1 2 3]
 [2 3 1]
 [3 1 2]]
[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [27]:
def mul(A, B):

    if len(A[0]) != len(B):
        raise "aaa"
    l = len(A[0])
    resmat = np.array([[0 for _ in range(len(A[0]))] for __ in range(len(B))])
    for i in range(len(A[0])):
        for j in range(len(B)):
            for k in range(len(B)):
                resmat[i][j] += A[i][k]*B[k][j]
    return resmat
mul(A, A)

array([[14, 11, 11],
       [11, 14, 11],
       [11, 11, 14]])

In [36]:
def matpow(A, n):
    if n == 0:
        return np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
    resmat = A
    for i in range(n-1):
        resmat = mul(resmat, A)
    return resmat

In [39]:
matpow(A, 0)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
# calculate fibonacci
n = 10
def rec_fib(n):
    if n == 0 or n == 1:
        return 1
    else:
        return rec_fib(n-1) + rec_fib(n-2)

fib = np.array([[1, 1], [1, 0]])
print(matpow(fib, n)[0][0], rec_fib(n))

89 89
